### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by diegodem** [iHardRock/dpdk_dump#1]
Hi, I try to compile with `g++ dpdk_dump.cpp -o dpdk_dump` but I get `dpdk_dump.h:6:21: fatal error: dynamic.h: No such file or directory
compilation terminated.`
Directory /external/dynamic is empty, maybe this is the problem.
Thank you

**Comment by iHardRock** [comment]
You must  init submodules first right after clone.
dynamic.h is standalone project https://github.com/iHardRock/dynamic
